import Link from 'next/link';
import { ArrowUpRight, Check, MapPin, Clock3 } from 'lucide-react';
import { getSearchListings, latestSearch, previousDedupeKeys } from '@minnow/db';
import { requireUser } from '@/lib/auth/session';
export const dynamic = 'force-dynamic';
export default async function ListingsPage() {
  const user = await requireUser(); const run = await latestSearch(user.id);
  if (!run) return <><div className="page-heading"><h1>Your shortlist</h1></div><div className="empty-results"><h3>Your next step starts with a hunt.</h3><p>No completed hunts yet. Set your preferences and discover live openings.</p><Link href="/dashboard" className="primary-button">Start a hunt</Link></div></>;
  const [listings, previous] = await Promise.all([getSearchListings(run.id,user.id), previousDedupeKeys(user.id,run.id)]);
  const old = new Set(previous);
  return <><div className="page-heading"><h1>Your shortlist</h1><p>{listings.length} ranked openings · {run.cache_hit ? 'cached hunt' : 'live hunt'} · {new Date(run.created_at).toLocaleString()}</p></div>{!listings.length && <div className="empty-results"><h3>No matches in this current.</h3><p>Try broader preferences. Hidden listings are omitted from your shortlist.</p><Link className="secondary-button" href="/dashboard">Adjust your hunt</Link></div>}<div className="job-list">{listings.map(job => <article className="job-card persisted-card" key={job.id}><div className="company-avatar blue">{job.company.slice(0,2).toUpperCase()}</div><div className="job-main"><div className="job-company"><span>{job.company}</span><span className="source-tag">{job.source_name}</span>{previous.length>0 && !old.has(job.dedupe_key) && <span className="new-badge">New since last hunt</span>}</div><h3>{job.title}</h3><div className="job-meta"><span><MapPin size={14} />{job.location || 'Not stated'}</span><span>{job.seniority.replace('_',' ')}</span><span>{job.work_mode}</span></div><p className="job-snippet">{job.snippet}</p><div className="match-reasons">{job.match_reasons.map(reason => <span key={reason}><Check size={12} />{reason}</span>)}</div><div className="job-foot"><span>{job.visa_signal==='sponsors' ? 'Sponsorship mentioned' : job.visa_signal==='no_sponsor' ? 'No sponsorship' : 'Sponsorship not stated'}</span><span><Clock3 size={12} /> Read {new Date(job.fetched_at).toLocaleString()}</span><a href={job.source_url} target="_blank" rel="noreferrer">Source</a></div></div><div className="job-actions"><span className="fit-label">{Math.round(Number(job.score))} fit</span><a className="apply-button" href={job.apply_url} target="_blank" rel="noreferrer">Apply <ArrowUpRight size={15} /></a></div></article>)}</div><div className="run-footer">{run.search_count} searches · {run.fetch_count} fetches · {run.agent_count} Agent runs {run.cache_hit && '· cache replay, no new endpoint calls'}</div></>;
}
