import { spawn } from 'node:child_process';
import { createRequire } from 'node:module';
const [app, ...args] = process.argv.slice(2);
if (!['web', 'observatory'].includes(app)) throw new Error('Choose web or observatory.');
const require = createRequire(new URL(`../apps/${app}/package.json`, import.meta.url));
const env = { ...process.env };
if (app === 'observatory') delete env.TINYFISH_API_KEY;
const child = spawn(process.execPath, [require.resolve('next/dist/bin/next'), ...args], { stdio: 'inherit', env });
for (const signal of ['SIGINT', 'SIGTERM']) process.on(signal, () => child.kill(signal));
child.on('error', error => { console.error(error.message); process.exitCode = 1; });
child.on('exit', (code, signal) => { process.exitCode = code ?? (signal === 'SIGINT' ? 130 : 1); });
